# Generated by Django 3.2 on 2023-11-04 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('release_login_after', models.DateTimeField(blank=True, null=True)),
                ('failed_recovery_attempts', models.IntegerField(default=0)),
                ('release_recovery_after', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='User_recovery_codes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='recovery_code_id')),
                ('code', models.CharField(max_length=6, verbose_name='recovery_code')),
                ('is_used', models.BooleanField(default=False, verbose_name='is_used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('valid_until', models.DateTimeField(auto_now_add=True, verbose_name='valid_until')),
                ('email_response', models.CharField(blank=True, max_length=255, null=True, verbose_name='email_response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User_recovery_codes',
                'db_table': 'user_recovery_codes',
            },
        ),
        migrations.CreateModel(
            name='Failed_login_attempts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ip_address', models.CharField(max_length=255, verbose_name='ip_address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Failed_login_attempts',
                'db_table': 'failed_login_attempts',
            },
        ),
    ]
